//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input Actions/User Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Input
{
    public partial class @UserInput: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @UserInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""User Input"",
    ""maps"": [
        {
            ""name"": ""Session"",
            ""id"": ""ca24cd42-9211-47b2-942e-799b0db23dbe"",
            ""actions"": [
                {
                    ""name"": ""CallMenu"",
                    ""type"": ""Button"",
                    ""id"": ""8adfbe48-8388-4118-855b-f93adf0cc563"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlidePrev"",
                    ""type"": ""Button"",
                    ""id"": ""8575cda9-f5f6-4509-8dab-2f212c4de16d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlideNext"",
                    ""type"": ""Button"",
                    ""id"": ""e62fdce2-12b5-442e-a818-58c99b9ab8c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5ff4c5d8-a2fe-48e9-976c-66bfad0225d3"",
                    ""path"": ""<XRController>{LeftHand}/{GripButton}"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CallMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd3f2d9e-0ed6-4f64-887f-e1306771cb3e"",
                    ""path"": ""<XRController>{RightHand}/{GripButton}"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CallMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f514ee98-e650-4d97-87a7-bf9a9a5bb0c0"",
                    ""path"": ""<XRController>{LeftHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlidePrev"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1668468e-a4cc-4a9e-a179-91df47a74125"",
                    ""path"": ""<XRController>{RightHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlidePrev"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a549123-6613-421b-9ce7-53674b24b6a9"",
                    ""path"": ""<XRController>{LeftHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlideNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cefdf509-8123-46d5-8ebf-e6091854564d"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlideNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Session
            m_Session = asset.FindActionMap("Session", throwIfNotFound: true);
            m_Session_CallMenu = m_Session.FindAction("CallMenu", throwIfNotFound: true);
            m_Session_SlidePrev = m_Session.FindAction("SlidePrev", throwIfNotFound: true);
            m_Session_SlideNext = m_Session.FindAction("SlideNext", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Session
        private readonly InputActionMap m_Session;
        private List<ISessionActions> m_SessionActionsCallbackInterfaces = new List<ISessionActions>();
        private readonly InputAction m_Session_CallMenu;
        private readonly InputAction m_Session_SlidePrev;
        private readonly InputAction m_Session_SlideNext;
        public struct SessionActions
        {
            private @UserInput m_Wrapper;
            public SessionActions(@UserInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @CallMenu => m_Wrapper.m_Session_CallMenu;
            public InputAction @SlidePrev => m_Wrapper.m_Session_SlidePrev;
            public InputAction @SlideNext => m_Wrapper.m_Session_SlideNext;
            public InputActionMap Get() { return m_Wrapper.m_Session; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(SessionActions set) { return set.Get(); }
            public void AddCallbacks(ISessionActions instance)
            {
                if (instance == null || m_Wrapper.m_SessionActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_SessionActionsCallbackInterfaces.Add(instance);
                @CallMenu.started += instance.OnCallMenu;
                @CallMenu.performed += instance.OnCallMenu;
                @CallMenu.canceled += instance.OnCallMenu;
                @SlidePrev.started += instance.OnSlidePrev;
                @SlidePrev.performed += instance.OnSlidePrev;
                @SlidePrev.canceled += instance.OnSlidePrev;
                @SlideNext.started += instance.OnSlideNext;
                @SlideNext.performed += instance.OnSlideNext;
                @SlideNext.canceled += instance.OnSlideNext;
            }

            private void UnregisterCallbacks(ISessionActions instance)
            {
                @CallMenu.started -= instance.OnCallMenu;
                @CallMenu.performed -= instance.OnCallMenu;
                @CallMenu.canceled -= instance.OnCallMenu;
                @SlidePrev.started -= instance.OnSlidePrev;
                @SlidePrev.performed -= instance.OnSlidePrev;
                @SlidePrev.canceled -= instance.OnSlidePrev;
                @SlideNext.started -= instance.OnSlideNext;
                @SlideNext.performed -= instance.OnSlideNext;
                @SlideNext.canceled -= instance.OnSlideNext;
            }

            public void RemoveCallbacks(ISessionActions instance)
            {
                if (m_Wrapper.m_SessionActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ISessionActions instance)
            {
                foreach (var item in m_Wrapper.m_SessionActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_SessionActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public SessionActions @Session => new SessionActions(this);
        public interface ISessionActions
        {
            void OnCallMenu(InputAction.CallbackContext context);
            void OnSlidePrev(InputAction.CallbackContext context);
            void OnSlideNext(InputAction.CallbackContext context);
        }
    }
}
